# Generated by Django 2.1.2 on 2019-01-02 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthychoiceapp', '0002_bookmarkproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmarkproduct',
            name='obj',
        ),
        migrations.RemoveField(
            model_name='bookmarkproduct',
            name='user',
        ),
        migrations.DeleteModel(
            name='BookmarkProduct',
        ),
    ]
