# Generated by Django 2.1.2 on 2019-01-02 13:04

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthychoiceapp', '0004_shoppinglist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='shoppinglist',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
