# Generated by Django 2.1.2 on 2019-01-02 13:50

import ckeditor.fields
import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthychoiceapp', '0006_auto_20190102_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
