# Generated by Django 2.1.2 on 2019-01-04 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthychoiceapp', '0008_favourite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favourite',
            name='products',
        ),
        migrations.RemoveField(
            model_name='favourite',
            name='recipes',
        ),
        migrations.RemoveField(
            model_name='favourite',
            name='user',
        ),
        migrations.DeleteModel(
            name='Favourite',
        ),
    ]
