# Generated by Django 2.1.2 on 2019-01-04 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthychoiceapp', '0010_bookmark_favourite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favourite',
            name='bookmarks',
        ),
        migrations.AddField(
            model_name='favourite',
            name='products',
            field=models.ManyToManyField(to='healthychoiceapp.Product'),
        ),
        migrations.AddField(
            model_name='favourite',
            name='recipes',
            field=models.ManyToManyField(to='healthychoiceapp.Recipe'),
        ),
        migrations.DeleteModel(
            name='Bookmark',
        ),
    ]
