# Generated by Django 2.1.2 on 2019-01-09 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthychoiceapp', '0011_auto_20190104_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(),
        ),
    ]
